// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 1.6.0 by WSRD Tencent.
// Generated from `DataMoniterServant.jce'
// **********************************************************************

package com.qq.bookbase.datamoniterserver.datamoniterservant;

public interface DataMoniterServantPrx
{
    public int test();

    public int test(java.util.Map __ctx);

    public void async_test(com.qq.bookbase.datamoniterserver.datamoniterservant.DataMoniterServantPrxCallback callback);

    public void async_test(com.qq.bookbase.datamoniterserver.datamoniterservant.DataMoniterServantPrxCallback callback, java.util.Map __ctx);


}
